//
// Created by ros on 3/18/18.
//

#ifndef OBJECT_DETECT_DETECTION_MODEL_TESTER_H
#define OBJECT_DETECT_DETECTION_MODEL_TESTER_H
#include "ORB_Featurizer.h"

#endif //OBJECT_DETECT_DETECTION_MODEL_TESTER_H
